f-dangel/backpack

.gitignore
.travis.yml
README.md
requirements-dev.txt

Add test coverage with [`coveralls`](https://coveralls.io/).
Coverage report from the command line:
```
pytest -vx --cov=backpack/ .
```

Test coverage

---

backpack/extensions/firstorder/batch_l2_grad/__init__.py
docs/rtd/extensions.html

Fix documentation of `BatchL2Grad`. The squared L2 norm of individual gradients is computed. Thanks @frhrdr for pointing out this problem

Batch l2 doc error

---

backpack/hessianfree/hvp.py
examples/example_hessian_matrix.py
examples/example_hessian_vector_product.py

Add argument to pass gradients to the Hessian-vector product.
If the gradients of `f` with respect to `params` have already been computed from a `f.backward(create_graph=True)` call, they can be recycled.

Hvp allow gradients

---

.darglint
.github/workflows/lint.yaml
.pre-commit-config.yaml
.pydocstyle
README-dev.md
backpack/utils/ein.py
makefile
requirements/lint.txt

This PR introduces `darglint` and `pydocstyle` as development tools to check existence/completeness/style of docstrings. More notes on development standards are listed in the [developer manual](https://github.com/f-dangel/backpack/blob/docstring-standards/README-dev.md).
Add GitHub actions and `pre-commit` hooks for the following `make` tasks:
```
make pydocstyle-check 
make darglint-check
```

Docstring standards

---

backpack/core/derivatives/elementwise.py

We need to investigate what happens if an activation layer modifies its input inplace. For now, this PR raises an exception if `inplace=True` is attempted.

No inplace modification

---

backpack/core/derivatives/__init__.py
backpack/core/derivatives/basederivatives.py
backpack/core/derivatives/crossentropyloss.py
backpack/core/derivatives/mseloss.py
test/test_second_order_warnings.py
test/test_sqrt_hessian.py
test/test_sqrt_hessian_sampled.py
test/test_sum_hessian.py

Cleanup of #56 and #55;
- Raise warning if the loss has been modified beyond the last torch.nn loss module
- Raise warning if `backward`is called on non-scalar quantity
- Raise exception if CrossEntropy or MSE are used with not-yet-implemented parameters (MSE between vectors, CrossEntropy with `ignore_index` or `weight`
- Add test for expected behavior

Sanity checks for second order backpropagation

---

.travis.yml
README-dev.md
README.md
requirements.txt
setup.py

* Use latest `torch` release (`1.6`)
* Remove `python3.5` from tests and add `python3.8`
* Update requirements and READMEs
Minor 
* Remove manual fix of `pillow` in travis
Background: PyTorch will drop support for python 3.5 with the [1.6 release](https://github.com/pytorch/pytorch/releases/tag/v1.6.0) (`CTRL f` "Dropped support for Python <= 3.5").

Deprecate python35

---

backpack/core/derivatives/conv_transposend.py
backpack/core/derivatives/convnd.py
test/core/derivatives/convolution_settings.py
test/core/derivatives/derivatives_test.py
test/extensions/firstorder/firstorder_settings.py

Added test settings (New format), for `extensions/firstorder`

Additional test settings for non-default hyperparameters

---

backpack/core/derivatives/avgpool2d.py
backpack/core/derivatives/batchnorm1d.py
backpack/core/derivatives/crossentropyloss.py
backpack/core/derivatives/dropout.py
backpack/core/derivatives/elu.py
backpack/core/derivatives/flatten.py
backpack/core/derivatives/leakyrelu.py
backpack/core/derivatives/linear.py
backpack/core/derivatives/logsigmoid.py
backpack/core/derivatives/maxpool2d.py
backpack/core/derivatives/mseloss.py
backpack/core/derivatives/relu.py
backpack/core/derivatives/selu.py
backpack/core/derivatives/sigmoid.py
backpack/core/derivatives/tanh.py
backpack/core/derivatives/zeropad2d.py

One more clean-up in the core. The mapping of `nn.Module`s to derivatives is defined in `backpack/core/derivatives/__init__.py` and hence `get_modules` is redundant

[core] Remove get_module

---

backpack/core/derivatives/convnd.py

This is a temporary change to compare `save_memory=False` with `save_memory=True` with our continuous benchmarking suite (https://f-dangel.github.io/backpack-benchmark/).
After updating the benchmarks and inspecting the results, it must be evaluated which choice should be kept as default.

[core] set default behavior of save_memory to True

---

backpack/extensions/__init__.py
backpack/extensions/secondorder/__init__.py
backpack/extensions/secondorder/diag_ggn/__init__.py
test/implementation/implementation_bpext.py
test/interface_test.py

- Remove import of parent class `DiagGGN`
- Make parent class non-functioning by removing default `savefield` and `loss_hessian_strategy`

Minor cleanup of Diagonal GGN extensions

---

backpack/core/derivatives/convnd.py

Resets the `save_memory` switch to the original value `False`. I will explain the switch in a future use case example together with our 'recommendations' how and when to use it, and a link to the benchmark.

[core] Don't save memory in convolution weight_jac_t by default

---

requirements/test.txt

The PyPI release of `pytorch_memlab` does not catch a `RuntimeError` in `torch.cuda.reset_peak_memory_stats`. This causes the tests to break with the release of `torch==1.8.0`. The problem seems to have been fixed in [this commit](https://github.com/Stonesjtu/pytorch_memlab/commit/004895fb5e602daed6a83e1a7e1bcffa3c950997).
This PR modifies the installation source of `pytorch_memlab` to use a commit with the above fix.

[TEST] Use GitHub installation source for pytorch_memlab

---

backpack/__init__.py
test/core/derivatives/problem.py

The output of an RNN module is tuple (output, h_n) ([RNN](https://pytorch.org/docs/stable/generated/torch.nn.RNN.html))
Similarly the output of LSTM and GRU is (output, ...) ([LSTM](https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html), [GRU](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html))
Therefore, this output has to be reduced in the backward hook to be compatible with backpack calls.

in preparation of support for RNN, reduce output of each module if tuple

---

backpack/extensions/firstorder/batch_grad/batch_grad_base.py
backpack/extensions/firstorder/gradient/base.py

To be more flexible with parameter names, refactor the firstorder extension such that arbitrary parameter names are supported.
Adding a support for a new module would then not require any additional changes to the firstorder modules for batch_grad.
Please review whether the docstrings are sufficient to understand the structure and purpose.
Please review whether the other firstorder modules should also be refactored.

Automate parameter function creation of BatchGrad and Grad extractors

---

.github/workflows/lint.yaml
.github/workflows/test.yaml
fully_documented.txt
makefile

Introduce partial format tests. The files that must be fully documented are defined in fully_documented.txt. This file is going to be populated later.
The tests are now run on Python 3.7 - 3.9. This is because later pull requests will use type hints using [PEP 563](https://www.python.org/dev/peps/pep-0563/) that was introduced in Python 3.7. These later pull requests will lead to BackPACK requiring python version 3.7 or higher.

Partial format tests

---

docs_src/examples/use_cases/example_convolution_save_memory.py
docs_src/examples/use_cases/example_save_memory_convolutions.py
requirements/docs.txt

Add a use case explaining how to use Owkin's VJPs for convolutions over BackPACK's default.

Save memory use case

---

.github/workflows/lint.yaml
fully_documented.txt
makefile

Fully documented files are added to `fully_documented.txt`. Once the
entire code base is documented, the partial checks can be removed, and
the full tests be turned on.
Taken from 91e85e5f6e49d4cd5e0c726e02fa62d3014a27d7.

[CI] Introduce partial docstring checks

---

.coveragerc
backpack/core/derivatives/rnn.py
backpack/custom_module/__init__.py
backpack/custom_module/permute.py
backpack/custom_module/reduce_tuple.py
backpack/extensions/firstorder/batch_grad/__init__.py
backpack/extensions/firstorder/batch_grad/rnn.py
backpack/extensions/firstorder/batch_l2_grad/__init__.py
backpack/extensions/firstorder/batch_l2_grad/rnn.py
backpack/extensions/firstorder/gradient/__init__.py
backpack/extensions/firstorder/gradient/rnn.py
backpack/extensions/firstorder/sum_grad_squared/__init__.py
backpack/extensions/firstorder/sum_grad_squared/rnn.py
backpack/extensions/firstorder/sum_grad_squared/sgs_base.py
backpack/extensions/firstorder/variance/__init__.py
backpack/extensions/firstorder/variance/rnn.py
backpack/extensions/firstorder/variance/variance_base.py
fully_documented.txt
setup.py
test/extensions/firstorder/batch_grad/batchgrad_settings.py
test/extensions/firstorder/firstorder_settings.py
test/extensions/implementation/autograd.py
test/extensions/problem.py

Add support for all first order extensions for RNN.
The ``axis_batch`` variable is removed from test problems in extensions.
Instead, modules ``Permute`` and ``ReduceTuple`` are introduced and can be used in a ``Sequential`` module.
Python version bumped to 3.7 because ``from __future__ import annotations`` is used.

RNN first order extensions

---

backpack/utils/conv.py
test/extensions/secondorder/secondorder_settings.py

This fixes  `groups ≠ 1` in diagonal curvature extensions. 
Resolves https://github.com/fKunstner/backpack-discuss/issues/86.

[utils] Support groups ≠ 1 in ConvNd extract_weight_diagonal

---

README.md
makefile
setup.cfg

There were some unforeseeable problems when trying to push to PyPI:
- The `test` folder was added to the package
- Pushing was not possible due to the GitHub dependency of `pytorch_memlab`
- Incorrectly specified URL in metadata
Auxiliary:
- Trying to install from `testpypi` raised errors of the following form:
```bash
ERROR: Could not find a version that satisfies the requirement einops>=0.3.0 (from backpack-for-pytorch) 
ERROR: No matching distribution found for einops>=0.3.0
```
I tried some fixes, but ultimately gave up. When I install the dependencies manually with `pip` before invoking
the `testpypi` install command, it seems to work. Thus I don't understand why the version specification fails
with the above error.

[FIX] PyPI release of `1.3.0`

---

backpack/extensions/__init__.py
backpack/extensions/secondorder/__init__.py
backpack/extensions/secondorder/sqrt_ggn/__init__.py
backpack/extensions/secondorder/sqrt_ggn/activations.py
backpack/extensions/secondorder/sqrt_ggn/base.py
backpack/extensions/secondorder/sqrt_ggn/convnd.py
backpack/extensions/secondorder/sqrt_ggn/convtransposend.py
backpack/extensions/secondorder/sqrt_ggn/dropout.py
backpack/extensions/secondorder/sqrt_ggn/flatten.py
backpack/extensions/secondorder/sqrt_ggn/linear.py
backpack/extensions/secondorder/sqrt_ggn/losses.py
backpack/extensions/secondorder/sqrt_ggn/padding.py
backpack/extensions/secondorder/sqrt_ggn/pooling.py
docs_src/examples/basic_usage/example_all_in_one.py
docs_src/rtd/extensions.rst
fully_documented.txt
makefile
test/extensions/implementation/autograd.py
test/extensions/implementation/backpack.py
test/extensions/implementation/base.py
test/extensions/secondorder/sqrt_ggn/__init__.py
test/extensions/secondorder/sqrt_ggn/test_sqrt_ggn.py

This PR adds an extension that computes the matrix square root of the generalized Gauss-Newton, using an exact factorization of the loss Hessian. For details, see Equation (3) of [this paper](https://arxiv.org/abs/2106.02624v1).
Auxiliary:
- `pytest`: Enable flag to report explanations of skipped tests
- Use `pytest fixtures` to separate the `set_up` and `tear_down` calls from the test (this should also be done for other tests, see https://github.com/fKunstner/backpack-discuss/issues/97)

[ADD] `SqrtGGNExact` extension

---

test/extensions/secondorder/secondorder_settings.py

Adds an architecture with a `torch.nn.Flatten` layer that does not introduce a node in the computation graph. In this case the backward hook for the `Flatten` module will be called at an unexpected stage, which must be addressed in the second-order extensions.
[This](https://coveralls.io/builds/40739633/source?filename=backpack%2Fextensions%2Fsecondorder%2Fsqrt_ggn%2Fflatten.py#L45) coverage report indicates that the new test suite did not include such a test case, whereas it seems to be covered by the old tests (the coverage report for second-order extensions that are tested in the old suite covers the linked branch in the module extensions for `Flatten`).

[TEST] Add setting where `Flatten` does not perform an operation

---

backpack/core/derivatives/linear.py
fully_documented.txt
test/core/derivatives/derivatives_test.py
test/core/derivatives/implementation/autograd.py
test/core/derivatives/linear_settings.py

The [derivatives of `nn.Linear`](https://github.com/f-dangel/backpack/blob/development/backpack/core/derivatives/linear.py) assume the layer input to have shape `[batch_size, in_features]`, and the output to have shape `[batch_size, out_features]`. However, in general inputs of shape `[batch_size, *, in_features]` with an arbitrary number of free axes `*` are allowed, see [the doc](https://pytorch.org/docs/stable/generated/torch.nn.Linear.html).
This PR adds support for additional axes to the `LinearDerivatives` in the `core`. Support for extensions will be provided through a separate PR.
Resolves the first part of https://github.com/fKunstner/backpack-discuss/issues/99.

[core] Support additional dimensions in input to `Linear`

---

backpack/core/derivatives/basederivatives.py
test/core/derivatives/derivatives_test.py
test/core/derivatives/implementation/autograd.py
test/core/derivatives/implementation/backpack.py
test/core/derivatives/implementation/base.py

Adds a test that checks `BaseDerivatives.hessian_is_zero` and improves documentation.
It is challenging to test the other properties, as they make additional assumptions about the function represented by a module (e.g. preserves input shape, elementwise function, scalar output). This hints that their interface needs to be improved in the future.
Close https://github.com/fKunstner/backpack-discuss/issues/62

[core] Add test of `hessian_is_zero` property

---

README-dev.md
README.md
backpack/extensions/secondorder/sqrt_ggn/base.py
backpack/extensions/secondorder/sqrt_ggn/flatten.py
backpack/extensions/secondorder/sqrt_ggn/losses.py
setup.cfg
test/test___init__.py

* Type annotations with cyclic imports, supported in `python3.7+`
* Update documentation and python requirement

[REQ] Fully deprecate python3.6

---

backpack/core/derivatives/basederivatives.py
backpack/core/derivatives/crossentropyloss.py
backpack/core/derivatives/mseloss.py
fully_documented.txt
test/core/derivatives/derivatives_test.py
test/core/derivatives/implementation/autograd.py
test/core/derivatives/implementation/backpack.py
test/extensions/implementation/backpack.py
test/utils/__init__.py

Prepares the core for #12.
Auxiliary:
- Make sqrt_MC tolerances stricter, add chunking
- Slightly rewrite sqrt_hessian functions for MSELoss

[core] Support sub-sampling in loss Hessian factorization

---

backpack/core/derivatives/basederivatives.py
backpack/core/derivatives/lstm.py
backpack/core/derivatives/rnn.py
backpack/core/derivatives/shape_check.py
backpack/custom_module/permute.py
backpack/extensions/firstorder/batch_grad/batch_grad_base.py
backpack/utils/subsampling.py
fully_documented.txt
test/core/derivatives/derivatives_test.py
test/core/derivatives/implementation/autograd.py
test/core/derivatives/problem.py
test/custom_module/__init__.py
test/custom_module/test_permute.py
test/extensions/firstorder/firstorder_settings.py
test/extensions/implementation/autograd.py
test/extensions/problem.py
test/extensions/secondorder/diag_ggn/diag_ggn_settings.py
test/extensions/utils.py
test/utils/skip_test.py
test/utils/test_subsampling.py

Sub-sampling relies on slicing tensors along their batch axis. So far we detect
the batch axis based on the module. However, BackPACK's custom `Permute`
module can alter the axes of its input tensor and therefore modify the batch axis
position. To account for this, the batch axis not only has to be determined based
on the module, but also on the direction of the tensor, i.e. `input` or `output`.
This PR introduces such a tensor-agnostic batch size detection. Progress on #12:
- Replace hard-coded batch axes in tests with dynamical ones
- Make `jac_t_mat_prod` tests work for `Permute` module
- Support arbitrary batch axes in `subsample`

[REF] Improve batch axis detection

---

backpack/core/derivatives/basederivatives.py

Fixes linting complaints from the latest `flake8` about missing declarations of abstract methods in abstract classes. 
**Edit:** Instead of declaring the abstract methods, we will ignore this warning. This is because some methods that are "marked" as abstract by raising a `NotImplementedError` are never implemented for certain modules (e.g. the residual-mat-prod for `Linear` layers, as it is never used). Explicitly marking them with `@abstractmethod` leads to failure of the code when instantiating an instance whose abstract method is not implemented.

[REF] Ignore warning to explicitly declare `abstractmethod`s

---

docs_src/splash/_includes/code-samples.html

Fixes #261.
Replaces
`from backpack import ..., X` <-> `from backpack import ..., extensions` and
`with backpack(X())` <-> `with backpack(extensions.X())`
on the [website examples](https://backpack.pt/).

[FIX] Use correct imports from backpack in website examples

---

test/extensions/secondorder/hbp/kfac_settings.py

By accident, they used batch size 3. Surprisingly, this was not caught by the test. The KFAC approximation was accurate enough for three samples.

[FIX] Use batch size 1 in KFAC ResNet tests

---

docs_src/examples/use_cases/example_batched_jacobians.py

Adds a use case demo for the documentation that explains computing batched Jacobians with BackPACK (#266).

[DOC] Add use case example: computing batched Jacobians

---

.github/workflows/test.yaml
backpack/core/derivatives/basederivatives.py
backpack/utils/convert_parameters.py
backpack/utils/examples.py
changelog.md
fully_documented.txt
setup.cfg

The test suite broke between `torch==1.11` and `torch==1.12` due to JVPs with `torch.autograd`. Until `1.11` their outcome used to be contiguous, which changed in `1.12`. Hence we cannot rely on the PyTorch built-in utility `parameters_to_vector`, which uses a `view` under the hood.
This PR makes the test suite compatible with `torch==1.12` (also run by the test CI).

[CI] Test with `torch=={1.9.0, 1.12.0}` and make tests compatible (master)

---

.github/workflows/test.yaml
backpack/core/derivatives/basederivatives.py
backpack/utils/convert_parameters.py
backpack/utils/examples.py
changelog.md
fully_documented.txt
setup.cfg

This PR is the equivalent of #276 for the development branch.

[CI] Test with `torch=={1.9.0, 1.12.0}` and make tests compatible (development)

---

backpack/utils/conv.py
setup.cfg

Long ago, I extracted the `im2col` code from BackPACK's convolution utilities into a [separate package](https://github.com/f-dangel/unfoldNd), where it is documented, tested, and benchmarked in more detail. This PR removes code from the BackPACK repository and relies on the extracted package instead.

[REF] Use `unfoldNd` package for input unfolding of convolutions

---

backpack/extensions/secondorder/hbp/conv2d.py
fully_documented.txt
test/extensions/secondorder/hbp/kfac_settings.py
test/extensions/secondorder/hbp/kfra_settings.py
test/extensions/secondorder/hbp/test_kfra.py
test/utils/skip_extension_test.py

This PR adds documentation to the `HBP` extension of `Conv2d` layers, which is responsible to compute `KFAC/KFLR/KFRA`. The docstrings draw connections to the notation in the [KFC paper](https://arxiv.org/pdf/1602.01407.pdf), and outline important differences, as well as improvements for consistency. It also adds a test case for `KFAC, KFLR` for which both approximations become exact.
Note to myself: I made notes how to connect Hessian backpropagation to `KFAC` for convolutions by imposing a Kronecker structure on the backpropagated quantity. This concept can also be applied to `KFRA` to achieve more consistency, but is currently not done by the code.

[DOC] Fully document `HBPConv2d`

---

.github/workflows/test.yaml
backpack/core/derivatives/basederivatives.py
backpack/core/derivatives/conv_transposend.py
backpack/core/derivatives/convnd.py
backpack/utils/__init__.py
backpack/utils/conv.py
backpack/utils/examples.py
setup.cfg
test/core/derivatives/implementation/autograd.py

Fixes #272.
- Adapt test CI to run tests with multiple torch versions, including 1.13
- Add `_grad_input_padding` function that was removed in 1.13 as utility and import if the installed torch version doesn't include it anymore
- `parameters_to_vector` stopped working for tensor lists with non-contiguous entries. Fix by calling `contiguous()` before vectorizing.
- torch raises a new exception (`TypeError`) when trying to compute the Hessian of a linear function. Fix by adding the new exception to the catched exceptions.

[FIX] Support for `torch>=1.13`

---

docs_src/examples/use_cases/example_retain_graph.py

Adds a tutorial for BackPACK's `retain_graph` option. It shows
how to distribute the GGN diagonal computation of an auto-
encoder architecture over multiple backward passes to reduce
peak memory. 
This use case recently came up in a discussion with @wiseodd
on Laplace approximations for auto-encoders (or any large
output neural network with square loss).

[DOC] Use case for `retain_graph`

---

.readthedocs.yml
setup.cfg

`system_packages` were deprecated on August 29, see https://blog.readthedocs.com/drop-support-system-packages/.

[CI] Drop `system_packages` in RTD config

---

backpack/hessianfree/ggnvp.py
backpack/hessianfree/hvp.py
changelog.md
fully_documented.txt
test/core/derivatives/implementation/autograd.py
test/implementation/implementation_autograd.py

This PR improves the Hessian-vector product's run time and memory consumption.
The old approach was using a JVP(VJP) approach, i.e. backward-forward.
The new approach uses a VJP(VJP) approach, i.e. backward-backward, which is more efficient according to my measurements (on a CPU roughly 2x faster, 20% less memory, see below).
The following script benchmarks an HVP on `resnet18` with ImageNet-shaped synthetic data:
```python
"""Benchmark BackPACK's Hessian-vector product."""
from time import perf_counter
import numpy
from memory_profiler import memory_usage
from torch import cuda, device, manual_seed, rand, rand_like, randint
from torch.nn import CrossEntropyLoss
from torchvision.models import resnet18
from backpack.hessianfree.hvp import hessian_vector_product
def hvp():
manual_seed(0) …
```

[REF] Change HVP from backward-forward to double-backward
