f-dangel/backpack

backpack/core/layers/__init__.py
backpack/extensions/curvmatprod/__init__.py
backpack/extensions/secondorder/diag_ggn/__init__.py
backpack/extensions/secondorder/diag_hessian/__init__.py
backpack/extensions/secondorder/hbp/__init__.py
examples/example_diag_ggn_optimizer.py
requirements.txt
test/interface_test.py
test/layers_test.py
test/problems.py
test/test_problems_convolutions.py
test/test_problems_padding.py
test/test_problems_pooling.py

Use PyTorch 1.2.0's Flatten layer (#6)

---

backpack/core/derivatives/utils.py
backpack/extensions/secondorder/utils.py
test/implementation/implementation_bpext.py
test/utils_test.py

Kronecker utilities

---

.travis.yml
requirements-dev.txt
test/automated_test.py

* Fix dependencies for Travis
* Increase MC samples from 200 to 500
This should fix #18

More samples for MC tests

---

docs_src/rtd/main-api.rst
docs_src/rtd/supported-layers.rst
docs_src/splash/_includes/code-samples.html

* Fix MNIST dimension 764 -> 784
* Improve consistency of features in code snippets

Fix html code samples

---

examples/example_all_in_one.py
examples/example_diag_ggn_exact.py
examples/example_diag_ggn_mc.py
examples/example_diag_hessian.py
examples/example_grad.py
examples/example_grad_2nd_moment.py
examples/example_grad_l2.py
examples/example_grad_var.py
examples/example_indiv_grads.py
examples/example_kfac.py
examples/example_kflr.py
examples/example_kfra.py
examples/utils.py

Add functioning example (MNIST, linear regression) scripts for all quantities

More examples

---

backpack/core/derivatives/conv2d.py
test/bugfixes_test.py

Issue: #30 
Add a test to check the stride issue and a fix for the `Conv2dDerivatives`

Conv2d derivative issues #30 - fix

---

backpack/core/derivatives/basederivatives.py
backpack/core/derivatives/batchnorm1d.py
backpack/extensions/curvature.py
backpack/extensions/curvmatprod/cmpbase.py
test/automated_bn_test.py

* Restructure multiplication into GGN and residual term
* Add support for layers with non-diagonal curvature information, such as `BatchNorm`
* Prepare tests and code for integration of `BatchNorm1d`

Restructure cmp

---

backpack/core/derivatives/avgpool2d.py
backpack/core/derivatives/batchnorm1d.py
backpack/core/derivatives/conv2d.py
backpack/core/derivatives/crossentropyloss.py
backpack/core/derivatives/elementwise.py
backpack/core/derivatives/linear.py
backpack/extensions/curvmatprod/cmpbase.py
backpack/extensions/firstorder/batch_l2_grad/conv2d.py
backpack/extensions/firstorder/batch_l2_grad/linear.py
backpack/extensions/firstorder/sum_grad_squared/conv2d.py
backpack/extensions/firstorder/sum_grad_squared/linear.py
backpack/extensions/secondorder/diag_hessian/diag_h_base.py
backpack/extensions/secondorder/hbp/conv2d.py
backpack/extensions/secondorder/hbp/linear.py
backpack/utils/conv.py
backpack/utils/ein.py
backpack/utils/kroneckers.py
backpack/utils/linear.py
requirements.txt
test/utils_test.py

Remove opt einsum

---

test/extensions/firstorder/batch_grad/batchgrad_settings.py
test/extensions/firstorder/batch_grad/test_batchgrad.py
test/extensions/problem.py

The initial pull request includes refactoring the test suite for extensions including documentation.
`Yet to add`: Additional settings

Test extensions

---

test/extensions/firstorder/batch_grad/batchgrad_settings.py
test/extensions/implementation/autograd.py
test/extensions/problem.py

> Function to determine the factor
> Settings with "sum" and "mean"

functionality for loss(reduction = "mean"/"sum")

---

backpack/extensions/firstorder/batch_grad/__init__.py
backpack/extensions/firstorder/batch_grad/conv1d.py
backpack/extensions/firstorder/batch_grad/conv3d.py
backpack/extensions/firstorder/batch_grad/conv_transpose1d.py
backpack/extensions/firstorder/batch_grad/conv_transpose2d.py
backpack/extensions/firstorder/batch_grad/conv_transpose3d.py
test/extensions/firstorder/batch_grad/batchgrad_settings.py
test/extensions/implementation/autograd.py
test/extensions/problem.py

Add extensions and tests for `ConvNd` and `ConvTransposeNd`
Co-authored-by: sbharadwajj <shrishabharadawaj5@gmail.com>

Conv batch grad extensions test (#91)

---

docs_src/examples/basic_usage/example_curvmatprod.py
docs_src/examples/use_cases/example_trace_estimation.py

- Basic example for extensions `GGNMP`, `HMP`, and `PCHMP`
- Use case example: Trace estimation with Hutchinson method

Curvmatprod example hutchinson

---

backpack/extensions/curvmatprod/pchmp/__init__.py
backpack/extensions/curvmatprod/pchmp/conv2d.py
backpack/extensions/curvmatprod/pchmp/linear.py
backpack/extensions/curvmatprod/pchmp/losses.py
backpack/extensions/curvmatprod/pchmp/pchmpbase.py
docs_src/examples/basic_usage/example_curvmatprod.py
docs_src/examples/use_cases/example_cg_newton.py
docs_src/examples/use_cases/example_diag_ggn_optimizer.py
docs_src/examples/use_cases/example_differential_privacy.py
test/implementation/implementation_bpext.py

- Add use case example for curvature-matrix products: Second-order optimization with CG
- Modify interface for positive-curvature Hessian-matrix products
- Slight modifications of other examples

Curvmatprod example cg newton

---

backpack/extensions/firstorder/batch_l2_grad/__init__.py
backpack/extensions/firstorder/batch_l2_grad/conv1d.py
backpack/extensions/firstorder/batch_l2_grad/conv3d.py
backpack/extensions/firstorder/batch_l2_grad/convtranspose1d.py
backpack/extensions/firstorder/batch_l2_grad/convtranspose2d.py
backpack/extensions/firstorder/batch_l2_grad/convtranspose3d.py
backpack/utils/conv.py
backpack/utils/conv_transpose.py
test/extensions/firstorder/batch_l2_grad/batchl2grad_settings.py
test/extensions/firstorder/batch_l2_grad/test_batchl2grad.py
test/extensions/implementation/autograd.py
test/extensions/implementation/backpack.py
test/extensions/implementation/base.py

1.  BatchL2Grad extensions for `Conv1d`, `Conv3d`, `ConvTranspose1d`, `ConvTranspose2d`, `ConvTranspose3d`
2. Test suite for the same

Batch l2 gradients: extensions 

---

test/core/derivatives/activation_settings.py
test/core/derivatives/convolution_settings.py
test/core/derivatives/linear_settings.py
test/core/derivatives/loss_settings.py
test/core/derivatives/padding_settings.py
test/core/derivatives/pooling_settings.py
test/core/derivatives/problem.py
test/utils/test_conv_settings.py
test/utils/test_conv_transpose_settings.py

1. Initial test pull request to check if old and new tests pass
2. old tests have not been removed yet

Change test core settings to new format

---

backpack/extensions/firstorder/batch_l2_grad/conv1d.py
backpack/extensions/firstorder/batch_l2_grad/conv2d.py
backpack/extensions/firstorder/batch_l2_grad/conv3d.py
backpack/extensions/firstorder/batch_l2_grad/conv_base.py
backpack/extensions/firstorder/batch_l2_grad/convnd.py
backpack/extensions/firstorder/batch_l2_grad/convtranspose1d.py
backpack/extensions/firstorder/batch_l2_grad/convtranspose2d.py
backpack/extensions/firstorder/batch_l2_grad/convtranspose3d.py
backpack/extensions/firstorder/batch_l2_grad/convtransposend.py
backpack/utils/conv.py
backpack/utils/conv_transpose.py

refactored `batch-l2-grad` to a single base class

ADD: refactord batch-l2

---

backpack/extensions/secondorder/diag_ggn/convnd.py

https://github.com/fKunstner/backpack-discuss/issues/82

Use `torch.nn.unfold` for `Conv2d`

---

makefile
test/automated_test.py
test/extensions/implementation/backpack.py
test/extensions/secondorder/diag_ggn/test_diag_ggn.py

MC-sampling tests were passing on CPU, but failed on GPU. This PR makes them pass again.
* Introduce chunking for MC-sampled `DiagGGNMC` to handle larger number of MC samples
* Triple number of MC samples to make GPU tests pass.

Fix gpu tests

---

backpack/utils/conv_transpose.py

https://github.com/fKunstner/backpack-discuss/issues/98

[bug, diagonal curvature] ConvTranspose uses forward pass to determine output shape

---

backpack/core/derivatives/convnd.py
test/core/derivatives/convolution_settings.py
test/core/derivatives/derivatives_test.py

Resolves https://github.com/fKunstner/backpack-discuss/issues/83.

[core] Support groups ≠ 1 in ConvNd weight_jac_t

---

.flake8
black.toml
docs_src/examples/basic_usage/example_all_in_one.py
docs_src/examples/use_cases/example_cg_newton.py
docs_src/examples/use_cases/example_custom_module.py
docs_src/examples/use_cases/example_first_order_resnet.py
docs_src/examples/use_cases/example_gradient_of_variance.py
docs_src/examples/use_cases/example_save_memory_convolutions.py
docs_src/examples/use_cases/example_trace_estimation.py

Adds examples/use cases to linting CI and resolves https://github.com/fKunstner/backpack-discuss/issues/79.

[doc] enforce auto-formatting & linting rules on examples

---

backpack/core/derivatives/elu.py
backpack/core/derivatives/selu.py
backpack/extensions/secondorder/diag_hessian/__init__.py
backpack/extensions/secondorder/diag_hessian/activations.py
test/extensions/secondorder/secondorder_settings.py

Fixes two bugs in the second-order derivatives of `ELU` and `SELU`.
Resolves https://github.com/fKunstner/backpack-discuss/issues/69.

[DiagHessian] Support `ELU` and `SELU`

---

docs_src/examples/basic_usage/example_all_in_one.py
docs_src/rtd/extensions.rst

Relevant parts copied from https://github.com/f-dangel/backpack/pull/146.
Resolves https://github.com/fKunstner/backpack-discuss/issues/90.
Resolves https://github.com/fKunstner/backpack-discuss/issues/91.

[DOC] Add per-sample curvatures to documentation

---

docs_src/rtd/good-to-know.rst
docs_src/rtd/supported-layers.rst

Resolves https://github.com/fKunstner/backpack-discuss/issues/78.

[DOC] Update supported layers and future features

---

backpack/__init__.py
backpack/extensions/firstorder/__init__.py
backpack/extensions/firstorder/batch_grad/__init__.py
backpack/extensions/firstorder/batch_l2_grad/__init__.py
backpack/extensions/firstorder/sum_grad_squared/__init__.py
backpack/extensions/firstorder/variance/__init__.py
backpack/extensions/secondorder/__init__.py
changelog.md
docs_src/rtd/conf.py
docs_src/rtd/main-api.rst
docs_src/rtd/supported-layers.rst

- Update changelog
- Update API and improve existing documentation for RTD

Prepare `1.3.0` release

---

backpack/core/derivatives/lstm.py
fully_documented.txt
test/core/derivatives/__init__.py
test/core/derivatives/derivatives_test.py
test/core/derivatives/lstm_settings.py

Derivatives and tests for LSTM.

LSTM derivatives and test

---

backpack/extensions/__init__.py
backpack/extensions/secondorder/__init__.py
backpack/extensions/secondorder/sqrt_ggn/__init__.py
backpack/extensions/secondorder/sqrt_ggn/losses.py
docs_src/examples/basic_usage/example_all_in_one.py
docs_src/rtd/extensions.rst
fully_documented.txt
test/extensions/implementation/autograd.py
test/extensions/implementation/backpack.py
test/extensions/implementation/base.py
test/extensions/secondorder/diag_ggn/test_batch_diag_ggn.py
test/extensions/secondorder/sqrt_ggn/test_sqrt_ggn.py

This pull request adds a Monte-Carlo approximation of the generalized Gauss-Newton/Fisher matrix square root.
Auxiliary:
- Improve type annotations/documentation in test suite

[ADD] `SqrtGGNMC` extension

---

backpack/core/derivatives/lstm.py
backpack/utils/__init__.py

Resolves https://github.com/fKunstner/backpack-discuss/issues/112.

[FIX] Check `LSTM` `proj_size` only for `torch>=1.8.0`

---

backpack/core/derivatives/adaptive_avg_pool_nd.py
backpack/utils/__init__.py
test/utils/skip_test.py

Set fix of the bug to torch 2.0 according to https://github.com/f-dangel/backpack/issues/184

[REF] set fix of AdaptiveAvgPoolBug3d to torch 2.0

---

.github/workflows/python-publish.yml

Automates PyPI release through GitHub action.

[CI] GitHub action for PyPI publish on GH release

---

backpack/core/derivatives/tanh.py
backpack/extensions/firstorder/batch_l2_grad/linear.py
backpack/extensions/firstorder/sum_grad_squared/linear.py
backpack/utils/linear.py
docs_src/examples/use_cases/example_cg_newton.py
test/core/derivatives/problem.py
test/extensions/implementation/autograd.py
test/extensions/implementation/hooks.py
test/extensions/problem.py
test/implementation/implementation_autograd.py
test/linear_test.py
test/test___init__.py

Update code format with latest `black` version.

[FMT] Apply `black==22.1.0`

---

changelog.md

[DOC] Update changelog (prepare release of `1.5.2`)

---

backpack/extensions/secondorder/diag_hessian/__init__.py
backpack/extensions/secondorder/diag_hessian/adaptive_avg_pool_nd.py
test/extensions/secondorder/diag_hessian/diagh_settings.py

Should fix #313 
I think it was just a case of a missing `module_ext`. 
Changes:
- Added `class DiagHAdaptiveAvgPoolNd(DiagHBaseModule)`
- Registered it in `class DiagHessian(SecondOrderBackpropExtension)`, `class BatchDiagHessian(SecondOrderBackpropExtension)`
- Added tests for the combination

Adaptive pooling for diagh
